### ISSUE TITLE
Can't get built-in STUN/TURN server to work

### ISSUE THREAD

**Issue by gabriel-eladi** [processone/docker-ejabberd#113]
Hello! I recently installed and set up the docker version of Ejabberd from `docker.io/ejabberd/ecs`. Here is my `docker-compose.yml` file:

<details>

```yaml
services:
  ejabberd:
    image: ejabberd/ecs
    container_name: ejabberd
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5223:5223"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "3478:3478" # stun/turn
      - "5349:5349" # stuns/turns
      - "49152-49500:49152-49500" # turn
    volumes:
      - ./config:/home/ejabberd/conf
      - ./db:/home/ejabberd/database
      - ./logs:/home/ejabberd/logs
      - ./upload:/home/ejabberd/upload
    depends_on:
      - ejabberd-postgres

  ejabberd-postgres:
    image: postgres:15-alpine
    container_name: ejabberd-postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/config/sql
      - ./postgres/docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ejabberd
      POSTGRES_USER: ejabberd
      POSTGRES_PASSWORD: secret-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
```
</details>

All the chat functions seem to work great. I then tried to set up the built-in STUN/TURN server to enable voice and video calls. I added/edited the following in my `ejabberd.yml` file:

<details>

```yaml
...
certfiles:
...
  - /home/ejabberd/conf/certs/stun-turn/fullchain.pem
  - /home/ejabberd/conf/certs/stun-turn/privkey.pem
...
...
listen:
...
  -
    port: 3478
    transport: udp
    module: ejabberd_stun
    use_turn: true
    ## The server's public IPv4 address:
    turn_ipv4_address: "my-external-ipv4-address"
    ## The server's public IPv6 address:
    # turn_ipv6_address: "2001:db8::3"
    turn_min_port: 49152
    turn_max_port: 49500
  -
    port: 5349
    transport: tcp
    module: ejabberd_stun
    use_turn: true
    tls: true
    turn_ipv4_address: "my-external-ipv4-address"
    turn_min_port: 49152
    turn_max_port: 49500
...
...
modules:
...
  mod_stun_disco:
    secret: my-secret
    services:
      -
        host: my-external-ipv4-address
        port: 3478
        type: stun
        transport: udp
        restricted: false
      -
        host: my-external-ipv4-address
        port: 3478
        type: turn
        transport: udp
        restricted: true
      -
        host: xmpp.mydomain.com
        port: 5349
        type: stuns
        transport: tcp
        restricted: false
      -
        host: xmpp.mydomain.com
        port: 5349
        type: turns
        transport: tcp
        restricted: true
...
```

</details>

I have the following ports forwarded on my router:
+ For XMPP: 5222, 5269, 5443
+ For STUN/TURN: 3478(tcp/udp), 5349(tcp/udp), 49152-49500(udp)

I also have the following DNS records set up:
```
+ A            | mydomain.com                                  | my-external-ipv4-address
+ CNAME | *.mydomain.com                               | mydomain.com
+ SRV        | _stun._tcp.xmpp.mydomain.com   | 0 0 3478 xmpp.mydomain.com
+ SRV        | _stun._udp.xmpp.mydomain.com | 0 0 3478 xmpp.mydomain.com
+ SRV        | _stuns._tcp.xmpp.mydomain.com | 0 0 5349 xmpp.mydomain.com
+ SRV        | _turn._tcp.xmpp.mydomain.com   | 0 0 3478 xmpp.mydomain.com
+ SRV        | _turn._udp.xmpp.mydomain.com | 0 0 3478 xmpp.mydomain.com
+ SRV        | _turns._tcp.xmpp.mydomain.com | 0 0 5349 xmpp.mydomain.com
```

I haven't been able to get the STUN/TURN server to work. Any advice would be greatly appreciated!

It is also worth noting that I have a Nginx Proxy Manager reverse proxy setup that manages my SSL certificates and through which all the HTTP/HTTPS traffic gets routed. However, the XMPP and STUN/TURN traffic should not get routed through it since (as far as I'm aware) they don't use ports 80/443.
