### ISSUE TITLE
ejabberd docker with Tailscale + serve.json

### ISSUE THREAD

**Issue by A4alli** [processone/docker-ejabberd#119]
hello ejabberd Dev and community. I managed to run ejabberd docker with Tailscale. I can login to admin portal page but cannot connect to the server with conversations app. here are the compose.yml and serve.json. I know I have missed things which I  need a guidance KINDLY

**compose.yml**
```
services:
  xmpp-tailscale:
    image: tailscale/tailscale:latest
    container_name: xmpp-tailscale
    cap_add:
      - NET_ADMIN
    hostname: chat
    environment:
      - TS_AUTHKEY=xyz
      - TS_AUTH_ONCE=true
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_CERT_DOMAIN=chat.forest-gentoo.ts.net
    networks:
      - xmpp
    restart: always
    volumes:
      - xmpp-tailscale-data:/var/lib/tailscale
      - ./serve_config/tailscale:/config

  xmpp-server:
    image: ejabberd/ecs
    container_name: xmpp-server
    volumes:
      - './ejabberd.yml:/home/ejabberd/conf/ejabberd.yml'
    restart: always
    ports:
      - 5443:5443
      - 5280:5280
    networks:
      - xmpp
    depends_on:
      - xmpp-tailscale

networks:
  xmpp:

volumes:
  xmpp-tailscale-data:
```

**serve.json**
```
{
  "TCP": {
    "5443": {
      "HTTPS": true
    },
    "5280": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:5443": {
      "Handlers": {
        "/": {
          "Proxy": "http://xmpp-server:5443"
        }
      }
    }
  }
}
```

kindly need suggestion
