### ISSUE TITLE
[critical] failed to start application 'riakc':

### ISSUE THREAD

**Issue by Hayyk** [processone/docker-ejabberd#18]
When trying to run a docker container using this image https://hub.docker.com/r/ejabberd/ecs/ I am getting error message 
```
"[critical] failed to start application 'riakc': {error,
                                      {"no such file or directory",
                                       "riakc.app"}}"
```
My ejabberd.yml includes:
```
riak_server: "riak"
riak_port: 8087
riak_pool_size: 10
riak_start_interval: 30
modules:
  mod_last:
    db_type: riak
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    db_type: riak
  mod_roster:
    db_type: riak
```
tried to build from your [repo](https://github.com/processone/docker-ejabberd/tree/master/ecs) using command ./build.sh 18.03 (also added {riak,true} in vars.config) but got the same problem.
How can I make riak enabled in ejabberd/ecs docker image?
