### ISSUE TITLE
create (admin) user from env vars

### ISSUE THREAD

**Issue by ccoenen** [processone/docker-ejabberd#58]
I would like to be able to create a default admin user from env vars. In the [readme](https://github.com/processone/docker-ejabberd/tree/master/ecs#creating-admin-user) it is stated that I need to `docker exec`, but I would like to have something like this in my `docker-compose.yml` instead:

```
  xmpp:
    image: ejabberd/ecs
    restart: unless-stopped
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - ./database:/home/ejabberd/database
    environment:
      - EJABBERD_ADMIN=admin
      - EJABBERD_PASS=someweirdpassword
```

This would run `docker exec -it ejabberd bin/ejabberdapi register --endpoint=http://127.0.0.1:5280/ --jid=admin@localhost --password=someweirdpassword` for me.

There's precedence for doing things like this, It is for example used in mariadb's docker images: https://github.com/docker-library/docs/tree/master/mariadb#environment-variables
