### ISSUE TITLE
How to run python script with docker-compose ejabberd

### ISSUE THREAD

**Issue by Carlososuna11** [processone/docker-ejabberd#75]
Hello make this docker-compose  and I have an external authorization script in python, what is the configuration that I have to do to make it run?
Docker-compose
```yml
...
  ejabberd:
    image: ejabberd/ecs:21.07
    restart: always
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - ERLANG_NODE_ARG=ejabberd@pictune_develop
      - CTL_ON_CREATE=register pictune_develop pictune_develop pictune_develop ;
                      module_install mod_offline_http_post ;
      - CTL_ON_START=stats registeredusers ;
                    status
    command: ["foreground"]
    # healthcheck:
    #   test: netstat -nl | grep -q 5222
    #   start_period: 5s
    #   interval: 5s
    #   timeout: 5s
    #   retries: 120
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./app/:/usr/src/app/
      - ./ejabberd/conf/:/home/ejabberd/conf
      - ejabberd_data:/home/ejabberd/database
      - ejabberd_logs:/home/ejabberd/logs
      - ejabberd_uplo:/home/ejabberd/upload
      - ./ejabberd/modules/mod_offline_http_post/:/home/ejabberd/.ejabberd-modules/mod_offline_http_post
      # - ./ejabberd/modules/mod_offline_http_post:/home/ejabberd/.ejabberd-modules/mod_offline_http_post
      # - ./ejabberd/modules/mod_offline_http_post/ebin/*:/home/ejabberd/lib/ejabberd-21.07/ebin/
      - ./ejabberd/auth/auth.py:/home/ejabberd/conf/auth/auth.py

...
```
Update: I saw my mistake, sorry :)
