### ISSUE TITLE
Cannot mount /conf to the host

### ISSUE THREAD

**Issue by sw-dev1** [processone/docker-ejabberd#95]
Using docker-compose.

Option 1:
Follow the [Customized Example](https://github.com/processone/docker-ejabberd/tree/master/ecs#customized-example):

```yaml
volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
```

Add (as suggested in [Volumes](https://github.com/processone/docker-ejabberd/tree/master/ecs#volumes)):

```
- ./conf:/home/ejabberd/conf/
```

Problem: /conf is not mounted to the host, instead created as a docker volume.

Option 2: 

```yaml
volumes:
      - ./conf:/home/ejabberd/conf/
```

The custom ejabberd.yml is in /conf on the host

Problem: `Log error: inetrc is missing`
The container starts with the default ejabberd.yml, conf is not mounted to the host, and not created as a docker volume.

**Comment by badlop** [comment]
I've tried now. Please check those examples:

With this example, the local file `conf/ejabberd.yml` is loaded to ejabberd, and used correctly:
```yaml
version: '3.7'
services:
  main:
    image: ejabberd/ecs:latest
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
      - ./conf/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
```

With this example, all the local `conf/` directory is mounted, this allows ejabberd to read ejabberd.yml, certificate files, additional configuration files, etc:
```yaml
version: '3.7'
services:
  main:
    image: ejabberd/ecs:latest
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
      - ./conf/:/home/ejabberd/conf/:ro
```
